/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Supplier;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Order;
import Business.OrdersDirectory;
import Business.Organization.ProductDepartment;
import Business.Product.ProductList;
import Business.WorkQueue.OrderWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.QualityAnalystRole.ProducInventoryJPanel;

/**
 *
 * @author Dell
 */
public class SupplierManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierManagerWorkAreaJPanel
     */
    JPanel userProcessContainer;
    //EcoSystem ecosystem;
    ProductList productList;
    Enterprise enterprise;
    ProductDepartment proddept;
    OrdersDirectory orders;
   // private OrdersDirectory orders;
    EcoSystem system;
    public SupplierManagerWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,EcoSystem system) {
                 initComponents();

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        //supplierName.setText(enterprise.getName());
        System.out.println(system.getNetworkList()+"----");
        //System.out.println(system.getNetworkList().get(0).getorderDirectory()+"--network--");
        orders = new OrdersDirectory();
        //System.out.println(orders);
        populateOrdersTable();
    }
    public void populatetblOrdrQ(){
        
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        
         model.setRowCount(0);
         
         for(OrderWorkRequest ordwrk:enterprise.getOrderQ().getorderworkRequestList()){
             
              Object[] row = new Object[5];
            row[0] = ordwrk.getProdId();
            row[1] = ordwrk.getProd();
            row[2] = ordwrk.getRequestDate();
            row[3] = ordwrk.getMessage();
            row[4] = ordwrk.getOrderStatus();

            model.addRow(row);
         
         }
        
        
    
    
    }
    
    public void populateOrdersTable(){
        
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        
        model.setRowCount(0);
       
        System.out.println(system.getNetworkList().get(0).getOrderDirectory()+"---");
        
        for(Order o :system.getNetworkList().get(0).getOrderDirectory().getOrderList()){
            
             System.out.println(o.toString()+"-----");
            Object[] row = new Object[9];
            row[0] = o.getOrderId();
            row[1] = o.getProductName();
            row[2] = o.getPrice();
            row[4] = o.getPrice()*o.getQuantity();
            row[3] = o.getQuantity();
            row[5] = o.getPlacedBy();
            row[6] = o.getAssigned_to();
            row[7] = o.getOrderDate();
            row[8] = o.getStatus();
            
            model.addRow(row);
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        btnInventory = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderQ = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setText("SupplierWorkArea");

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderId", "Product Name", "Price per Unit", "Quantity", "Total price", "created by", "assigned_to", "created date", "date_updated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.setRowMargin(24);
        jScrollPane1.setViewportView(orderTable);

        btnInventory.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        btnInventory.setText("Inventory");
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });

        tblOrderQ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "created Date", "Message", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblOrderQ);

        jLabel3.setText("Order Requests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(188, 188, 188)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInventory)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
 
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("", new SupplierInventoryJPanel(userProcessContainer, enterprise, system));
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable tblOrderQ;
    // End of variables declaration//GEN-END:variables
}
