/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.QualityAnalystRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.Manufacture;
import Business.Network.Network;
import Business.Organization.ProductDepartment;
import Business.Organization.Organization;
import Business.Organization.QualityDepartment;
import Business.Organization.SalesDepartment;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProductTestRequest;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.prodDeptWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class QualityAnalystWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private QualityDepartment organization;
    private Enterprise enterprise;

    /**
     * Creates new form QualityAnalystWorkAreaJPanel
     */
    public QualityAnalystWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, QualityDepartment organization, Enterprise enterprise, EcoSystem business) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.userAccount = account;
        this.business = business;
        this.enterprise = enterprise;
        populateTable();
        //populateNetworkComboBox();
    }
    
   

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getSender();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();
            row[4] = request.getMessage();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        txtProdId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        senderTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentsTextField = new javax.swing.JTextArea();
        updateButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JComboBox();
        networkRequest = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setRowHeight(24);
        jScrollPane1.setViewportView(workRequestJTable);
        if (workRequestJTable.getColumnModel().getColumnCount() > 0) {
            workRequestJTable.getColumnModel().getColumn(0).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(1).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(2).setResizable(false);
            workRequestJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 670, 160));

        assignJButton.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        btnView.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        btnView.setText("view");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 110, 50));

        refreshJButton.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        btnInventory.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        btnInventory.setText("Inventory");
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 130, 50));
        add(txtProdId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 80, -1));

        jLabel6.setText("Product Id:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gabriola", 2, 24)); // NOI18N
        jLabel7.setText("Quantity");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));
        add(quantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 80, -1));

        jLabel9.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel9.setText("Sender:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 80, -1));
        add(senderTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 80, -1));

        jLabel10.setFont(new java.awt.Font("Gabriola", 2, 24)); // NOI18N
        jLabel10.setText("Comments");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        commentsTextField.setColumns(20);
        commentsTextField.setRows(5);
        jScrollPane2.setViewportView(commentsTextField);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        updateButton.setText("update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 599, 120, 50));

        jLabel11.setFont(new java.awt.Font("Gabriola", 2, 24)); // NOI18N
        jLabel11.setText("Status");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 80, 20));

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pass", "Fail" }));
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 90, -1));

        networkRequest.setText("Request Over Network");
        networkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkRequestActionPerformed(evt);
            }
        });
        add(networkRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel12.setText("Product Quality Analyst");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        request.setStatus("Quality Check in Process");
        request.setResult(txtStatus.getSelectedItem().toString());

        populateTable();

    }//GEN-LAST:event_assignJButtonActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        ProductTestRequest request = (ProductTestRequest) workRequestJTable.getValueAt(selectedRow, 0);

//        ProcessWorkRequestJPanel processWorkRequestJPanel = new ProcessWorkRequestJPanel(userProcessContainer, request);
//        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
        System.out.println(request.getProductId());
        txtProdId.setText(request.getProductId());
        txtProdId.setEditable(false);

        senderTextField.setText(request.getSender().getEmployee().getName());
        senderTextField.setEditable(false);


    }//GEN-LAST:event_btnViewActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ProductInventoryJPanel", new ProducInventoryJPanel(userProcessContainer, userAccount, organization, enterprise, business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
       int selectedRow = workRequestJTable.getSelectedRow();

       if (selectedRow < 0) {
           return;
       }

       ProductTestRequest request = (ProductTestRequest) workRequestJTable.getValueAt(selectedRow, 0);

       //request.setStatus("");
       int qtypassed = Integer.valueOf(quantityTextField.getText());

       //quantityTextField.setText(String.valueOf(request.getQuantity()));
       request.setMessage(commentsTextField.getText());
       quantityTextField.setEditable(false);
       commentsTextField.setEditable(false);
       //request.setResult("Completed");
       
       for(Network network:business.getNetworkList()){
           
                  for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
           System.out.println(enterprise.getOrganizationDirectory().getOrganizationList() + "-----");

           for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {

               System.out.println(organization);
               if (organization instanceof ProductDepartment) {
                   for (Product prod : ((ProductDepartment) organization).getProdList().getProductList()) {
                       //System.out.println(prod.toString());
                       if (prod.getProductId().equalsIgnoreCase(request.getProductId())) {
                           prod.setQuantity(qtypassed);
                       }

                   }
               }
           }


//            // work request code
     Organization org = null;

       if (request.getResult() == "Pass") {
           request.setStatus("Sent to Sales");

           //for()

           for (Organization organ : enterprise.getOrganizationDirectory().getOrganizationList()) {

               System.out.println(organ.toString());
               if (organ instanceof SalesDepartment) {
                   org = organ;
                   break;
               }
           }
           if (org != null) {
               org.getWorkQueue().getWorkRequestList().add(request);
               userAccount.getWorkQueue().getWorkRequestList().add(request);
           }

       } else {
           request.setStatus("Completed with rejection");
           for (Organization organ : enterprise.getOrganizationDirectory().getOrganizationList()) {

               System.out.println(organ.toString());
               if (organ instanceof ProductDepartment) {
                   org = organ;
                   break;
               }
           }
           if (org != null) {
               org.getWorkQueue().getWorkRequestList().add(request);
               userAccount.getWorkQueue().getWorkRequestList().add(request);
           }

       }
    populateTable();
            
            
            
            
        }
       
       }




    }//GEN-LAST:event_updateButtonActionPerformed

    private void networkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkRequestActionPerformed
        // TODO add your handling code here:
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ProductInventoryJPanel", new ProcessRequestToAnotherNetworkJPanel(userProcessContainer, userAccount, organization, enterprise, business));
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_networkRequestActionPerformed

    
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnView;
    private javax.swing.JTextArea commentsTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton networkRequest;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTextField senderTextField;
    private javax.swing.JTextField txtProdId;
    private javax.swing.JComboBox txtStatus;
    private javax.swing.JButton updateButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
